### ISSUE TITLE
`random` module is not safe for security use.

### ISSUE THREAD

**Issue by Wafelack** [naliliV2/Uncrackable#2]
As mentioned in the [random module documentation](https://docs.python.org/3/library/random.html), the `random` module is not safe for security use.

![image](https://user-images.githubusercontent.com/61330081/113489065-31807300-94c2-11eb-83c2-8d17e9dc365d.png)

I suggest to use the [`secrets`](https://docs.python.org/3/library/secrets.html) module, as the docs recommends.

Regards,
Wafelack.

**Comment by naliliV2** [comment]
I don't see how generating a random password is cryptography. Moreover, I see even less use for this post because it will be strictly the same function I will use aka random.

**Comment by Wafelack** [comment]
Ok, you can close the issue then.
